classdef (ConstructOnLoad) StingrayTDD < adi.internal.AXICoreTDD

    properties(Hidden)
        % HDL Channel mapping
        %   axi_tdd_0/tdd_channel_0 -> axi_data_offload_tx/sync_ext 
        %   axi_tdd_0/tdd_channel_1 -> axi_data_offload_rx/sync_ext 
        %   axi_tdd_0/tdd_channel_2  -> tdd_enabled 
        %   axi_tdd_0/tdd_channel_3  -> tdd_rx_mxfe_en 
        %   axi_tdd_0/tdd_channel_4  -> tdd_tx_mxfe_en 
        %   axi_tdd_0/tdd_channel_5  -> tdd_tx_stingray_en 
        channels = [...
            struct('name','FPGATxOffloadSync','channel',0,'hdl_name','axi_data_offload_tx/sync_ext'),...
            ...
            struct('name','FPGARxOffloadSync','channel',1,'hdl_name','axi_data_offload_rx/sync_ext'),...
            ...
            struct('name','FPGATDDEngine','channel',2,'hdl_name','tdd_enabled'),...
            ...
            struct('name','RxMxFE','channel',3,'hdl_name','tdd_rx_mxfe_en'),...
            ...
            struct('name','TxMxFE','channel',4,'hdl_name','tdd_tx_mxfe_en'),...
            ...
            struct('name','TxStingray','channel',5,'hdl_name','tdd_tx_stingray_en')...
        ];

    end
    
    methods
        function obj = StingrayTDD(varargin)
            setProperties(obj, nargin, varargin{:});
            obj.buildChannels();
        end

    end


end